// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKugVgrVLeXhQ2gcxjMiSSNs88WFXk_gM',
    appId: '1:13164877228:web:57c513b0da66fceda8d609',
    messagingSenderId: '13164877228',
    projectId: 'projectbatiksesa',
    authDomain: 'projectbatiksesa.firebaseapp.com',
    storageBucket: 'projectbatiksesa.firebasestorage.app',
    measurementId: 'G-6WYV51SXFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi3ImkOm24fKoYD9Zzi-iOOlDWzWSa05s',
    appId: '1:13164877228:android:53b75415d9668f03a8d609',
    messagingSenderId: '13164877228',
    projectId: 'projectbatiksesa',
    storageBucket: 'projectbatiksesa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACAKtW13FhhWE9mhTFuenTFTqiS2temXA',
    appId: '1:13164877228:ios:e8341b23ad110e1da8d609',
    messagingSenderId: '13164877228',
    projectId: 'projectbatiksesa',
    storageBucket: 'projectbatiksesa.firebasestorage.app',
    iosBundleId: 'com.example.batikSesaBojonegoroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACAKtW13FhhWE9mhTFuenTFTqiS2temXA',
    appId: '1:13164877228:ios:e8341b23ad110e1da8d609',
    messagingSenderId: '13164877228',
    projectId: 'projectbatiksesa',
    storageBucket: 'projectbatiksesa.firebasestorage.app',
    iosBundleId: 'com.example.batikSesaBojonegoroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKugVgrVLeXhQ2gcxjMiSSNs88WFXk_gM',
    appId: '1:13164877228:web:7566b326ac78876ea8d609',
    messagingSenderId: '13164877228',
    projectId: 'projectbatiksesa',
    authDomain: 'projectbatiksesa.firebaseapp.com',
    storageBucket: 'projectbatiksesa.firebasestorage.app',
    measurementId: 'G-7PXH4B5NQD',
  );
}
