import 'package:batik_sesa_bojonegoro_app/core/provider/penerimaan_provider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:heroicons/heroicons.dart';
import 'package:intl/intl.dart';
import 'package:batik_sesa_bojonegoro_app/core/model/penerimaan_model.dart';

class AddPenerimaanScreen extends ConsumerStatefulWidget {
  const AddPenerimaanScreen({super.key});

  @override
  ConsumerState<AddPenerimaanScreen> createState() =>
      _AddPenerimaanScreenState();
}

class _AddPenerimaanScreenState extends ConsumerState<AddPenerimaanScreen> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _tanggalController = TextEditingController();
  final TextEditingController _transaksiController = TextEditingController();
  final TextEditingController _pembeliController = TextEditingController();
  final TextEditingController _kuantitasController = TextEditingController();
  final TextEditingController _satuanController = TextEditingController();
  final TextEditingController _hargaSatuanController = TextEditingController();
  bool _isLoading = false;

  DateTime? _selectedDate;

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate ?? DateTime.now(),
      firstDate: DateTime(2000),
      lastDate: DateTime(2100),
    );
    if (picked != null && picked != _selectedDate) {
      setState(() {
        _selectedDate = picked;
        _tanggalController.text = DateFormat('dd MMM yyyy').format(picked);
      });
    }
  }

  Future<void> _submitForm() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() => _isLoading = true);

    try {
      if (_selectedDate == null) {
        throw Exception('Tanggal harus diisi');
      }

      final penerimaanBaru = PenerimaanModel(
        id: '', // Will be generated by Firebase
        tanggal: _selectedDate!.toIso8601String(),
        transaksi: _transaksiController.text.trim(),
        pembeli: _pembeliController.text.trim(),
        kuantitas: num.parse(_kuantitasController.text.trim()),
        satuan: _satuanController.text.trim(),
        hargaSatuan: num.parse(_hargaSatuanController.text.trim()),
        total:
            num.parse(_kuantitasController.text.trim()) *
            num.parse(_hargaSatuanController.text.trim()),
        keterangan: null,
      );

      final repository = ref.read(penerimaanRepositoryProvider);
      await repository.addPenerimaan(penerimaanBaru);

      if (!mounted) return;

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Penerimaan berhasil ditambahkan'),
          backgroundColor: Colors.green,
        ),
      );
      Navigator.pop(context);
    } catch (e) {
      if (!mounted) return;

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Gagal menambahkan penerimaan: ${e.toString()}'),
          backgroundColor: Colors.red,
        ),
      );
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  void dispose() {
    _tanggalController.dispose();
    _transaksiController.dispose();
    _pembeliController.dispose();
    _kuantitasController.dispose();
    _satuanController.dispose();
    _hargaSatuanController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Tambah Penerimaan'),
        centerTitle: true,
        leading: IconButton(
          icon: const HeroIcon(HeroIcons.arrowLeft),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Tanggal
              TextFormField(
                controller: _tanggalController,
                decoration: InputDecoration(
                  labelText: 'Tanggal',
                  border: const OutlineInputBorder(),
                  prefixIcon: const HeroIcon(HeroIcons.calendar),
                  suffixIcon: IconButton(
                    icon: const HeroIcon(HeroIcons.calendarDays),
                    onPressed: () => _selectDate(context),
                  ),
                ),
                readOnly: true,
                validator: (value) =>
                    value!.isEmpty ? 'Pilih tanggal penerimaan' : null,
              ),
              const SizedBox(height: 16),

              // Nama Transaksi
              TextFormField(
                controller: _transaksiController,
                decoration: const InputDecoration(
                  labelText: 'Nama Transaksi',
                  border: OutlineInputBorder(),
                  prefixIcon: HeroIcon(HeroIcons.shoppingBag),
                ),
                validator: (value) =>
                    value!.isEmpty ? 'Masukkan nama transaksi' : null,
              ),
              const SizedBox(height: 16),

              // Nama Pembeli
              TextFormField(
                controller: _pembeliController,
                decoration: const InputDecoration(
                  labelText: 'Nama Pembeli',
                  border: OutlineInputBorder(),
                  prefixIcon: HeroIcon(HeroIcons.user),
                ),
                validator: (value) =>
                    value!.isEmpty ? 'Masukkan nama pembeli' : null,
              ),
              const SizedBox(height: 16),

              // Kuantitas dan Satuan
              Row(
                children: [
                  Expanded(
                    flex: 2,
                    child: TextFormField(
                      controller: _kuantitasController,
                      decoration: const InputDecoration(
                        labelText: 'Kuantitas',
                        border: OutlineInputBorder(),
                        prefixIcon: HeroIcon(HeroIcons.hashtag),
                      ),
                      keyboardType: TextInputType.number,
                      validator: (value) =>
                          value!.isEmpty ? 'Masukkan kuantitas' : null,
                      onChanged: (_) => setState(() {}),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    flex: 3,
                    child: TextFormField(
                      controller: _satuanController,
                      decoration: const InputDecoration(
                        labelText: 'Satuan',
                        border: OutlineInputBorder(),
                        prefixIcon: HeroIcon(HeroIcons.scale),
                      ),
                      validator: (value) =>
                          value!.isEmpty ? 'Masukkan satuan' : null,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // Harga Satuan
              TextFormField(
                controller: _hargaSatuanController,
                decoration: const InputDecoration(
                  labelText: 'Harga Satuan',
                  border: OutlineInputBorder(),
                  prefixIcon: HeroIcon(HeroIcons.currencyDollar),
                  prefixText: 'Rp ',
                ),
                keyboardType: TextInputType.number,
                validator: (value) =>
                    value!.isEmpty ? 'Masukkan harga satuan' : null,
                onChanged: (_) => setState(() {}),
              ),
              const SizedBox(height: 24),

              // Total Preview
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.grey[100],
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text(
                      'Total:',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    Text(
                      _calculateTotal(),
                      style: const TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                        color: Colors.blue,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 24),

              // Submit Button
              ElevatedButton(
                onPressed: _isLoading ? null : _submitForm,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(10),
                  ),
                ),
                child: _isLoading
                    ? const SizedBox(
                        height: 24,
                        width: 24,
                        child: CircularProgressIndicator(
                          color: Colors.white,
                          strokeWidth: 3,
                        ),
                      )
                    : const Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          HeroIcon(HeroIcons.document, size: 20),
                          SizedBox(width: 8),
                          Text('Simpan Penerimaan'),
                        ],
                      ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  String _calculateTotal() {
    try {
      if (_kuantitasController.text.isNotEmpty &&
          _hargaSatuanController.text.isNotEmpty) {
        final kuantitas = num.parse(_kuantitasController.text);
        final harga = num.parse(_hargaSatuanController.text);
        final total = kuantitas * harga;
        return 'Rp ${NumberFormat('#,###').format(total)}';
      }
    } catch (e) {
      return 'Rp 0';
    }
    return 'Rp 0';
  }
}
